// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXh6d3Nnu_0ZwJ2dqgsjJmxOe6H0yglg',
    appId: '1:296079288919:web:d3229003a03c454db25112',
    messagingSenderId: '296079288919',
    projectId: 'medifinder-564fa',
    authDomain: 'medifinder-564fa.firebaseapp.com',
    storageBucket: 'medifinder-564fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHPCNDG83KRYE4qNeo-y7100MFaVFmgqA',
    appId: '1:296079288919:android:5f3daf027c4686e4b25112',
    messagingSenderId: '296079288919',
    projectId: 'medifinder-564fa',
    storageBucket: 'medifinder-564fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARXST86Tos8Kr_0TceEZJ_50X74pZDv7s',
    appId: '1:296079288919:ios:6a9f62bb13a62d78b25112',
    messagingSenderId: '296079288919',
    projectId: 'medifinder-564fa',
    storageBucket: 'medifinder-564fa.appspot.com',
    iosBundleId: 'com.group1.medifinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARXST86Tos8Kr_0TceEZJ_50X74pZDv7s',
    appId: '1:296079288919:ios:6a9f62bb13a62d78b25112',
    messagingSenderId: '296079288919',
    projectId: 'medifinder-564fa',
    storageBucket: 'medifinder-564fa.appspot.com',
    iosBundleId: 'com.group1.medifinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGXh6d3Nnu_0ZwJ2dqgsjJmxOe6H0yglg',
    appId: '1:296079288919:web:f5022e1b96a5fff6b25112',
    messagingSenderId: '296079288919',
    projectId: 'medifinder-564fa',
    authDomain: 'medifinder-564fa.firebaseapp.com',
    storageBucket: 'medifinder-564fa.appspot.com',
  );
}
